# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='nam',
        ),
    ]
