# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20171228_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='nam',
            new_name='name',
        ),
    ]
